name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI
on:
  push:
    tags:
    - '*'
jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-0

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1

    - name: Bump version to given tag in pyproject.toml
      run: |
        sed -i '0,/version =.*/s//version = "'"${{ github.event.release.tag_name }}"'"/' ./pyproject.toml

    - name: Commit version update to branch
      run: |
        git add pyproject.toml
        git commit -m "Change version in pyproject.tomll to ${{ github.event.release.tag_name }}"
        git push origin main

    - name: Install package including dev dependencies using Poetry
      run: poetry install

    - name: Publish to TestPyPi
      run: poetry publish --repository --build --username ${{ secrets.PYPI_API_TOKEN }} --dry-run
